In [1]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
X, y = iris.data, iris.target

print(f'{X.shape = }')
print(f'{y.shape = }')

X.shape = (150, 4)
y.shape = (150,)


In [2]:
from neural_network.decomposition import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=2)
X = lda.fit_transform(X, y)

In [3]:
from neural_network.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print(f'{X_train.shape = }')
print(f'{y_train.shape = }')
print(f'{X_test.shape = }')
print(f'{y_test.shape = }')

X_train.shape = (105, 2)
y_train.shape = (105,)
X_test.shape = (45, 2)
y_test.shape = (45,)


In [4]:
from neural_network.preprocess import OneHotEncoder, Scaler

labels = np.unique(y)
encoder = OneHotEncoder().fit(labels)
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)
print(f'Encoded {y_train.shape = }')
print(f'Encoded {y_test.shape = }')

scaler, X_train = Scaler().fit_transform(X_train, return_self=True)
X_test = scaler.transform(X_test)

Encoded y_train.shape = (105, 3)
Encoded y_test.shape = (45, 3)


In [5]:
from neural_network.layers.dense import Dense
from neural_network.model.sequential import Sequential

net = Sequential()

net.add(
    Dense(10, input_shape=2, activation='relu'),
    Dense(10, activation='tanh'),
    Dense(3, activation='softmax')
)

net.compile(cost='crossentropy', metrics=['accuracy_score'])

In [6]:
from neural_network.model_selection import KFold

kf = KFold(n_splits=3)

for train, validate in kf.split(X_train):
    net.fit(
        X_train[train],
        y_train[train],
        epochs=10,
        batch_size=5,
        validation_data=(X_train[validate], y_train[validate])
    )


Epoch  1/10
  Step  1/14 ... done
  Step  2/14 ... done
  Step  3/14 ... done
  Step  4/14 ... done
  Step  5/14 ... done
  Step  6/14 ... done
  Step  7/14 ... done
  Step  8/14 ... done
  Step  9/14 ... done
  Step 10/14 ... done
  Step 11/14 ... done
  Step 12/14 ... done
  Step 13/14 ... done
  Step 14/14 ... done

  Validation loss: 3.8902 accuracy_score: 0.4857
  Overall loss: 3.4667 accuracy_score: 0.3714

Epoch  2/10
  Step  1/14 ... done
  Step  2/14 ... done
  Step  3/14 ... done
  Step  4/14 ... done
  Step  5/14 ... done
  Step  6/14 ... done
  Step  7/14 ... done
  Step  8/14 ... done
  Step  9/14 ... done
  Step 10/14 ... done
  Step 11/14 ... done
  Step 12/14 ... done

  Validation loss: 3.3848 accuracy_score: 0.4857
  Overall loss: 2.6119 accuracy_score: 0.5286

Epoch  3/10
  Step  1/14 ... done
  Step  2/14 ... done
  Step  3/14 ... done
  Step  4/14 ... done
  Step  5/14 ... done
  Step  6/14 ... done
  Step  7/14 ... done
  Step  8/14 ... done
  Step  9/14 ... done

In [7]:
predictions = net.predict(X_test, classify=True)

print(f'{predictions.shape = }')

predictions.shape = (45, 3)


In [8]:
from neural_network.metrics import confusion_matrix
print('Confusion Matrix')
print(confusion_matrix(y_test, predictions))

Confusion Matrix
[[16  0  0]
 [ 0  8  2]
 [ 0  3 16]]


In [9]:
from neural_network.metrics import accuracy_score
print('Accuracy Score')
print(accuracy_score(y_test, predictions))

Accuracy Score
0.8888888888888888


In [10]:
from neural_network.metrics import accuracy_by_label
print('Accuracy by Label')
print(accuracy_by_label(y_test, predictions))

Accuracy by Label
[1.         0.72727273 0.88888889]
